INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (1, 1, 'Road Runner', 226, 1, 1);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (2, 1, 'Shame, Shame, Shame', 135, 1, 2);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (3, 1, 'Eyesight To The Blind', 191, 1, 3);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (4, 1, 'Baby, Please Don''t Go', 204, 1, 4);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (5, 1, 'Never Loved A Girl', 192, 1, 5);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (6, 1, 'Back Back Train', 263, 1, 6);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (7, 1, 'You Gotta Move', 331, 1, 7);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (8, 1, 'The Grind', 227, 1, 8);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (9, 1, 'I''m Ready', 255, 1, 9);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (10, 1, 'Temperature', 171, 1, 10);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (11, 1, 'Stop Messin'' Around', 272, 1, 11);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (12, 1, 'Jesus Is On The Main Line', 169, 1, 12);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (13, 2, 'Wasting My Time', 308, 1, 1);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (14, 2, 'All In My Head (Radio Edit)', 246, 1, 2);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (15, 2, 'Crawling', 234, 1, 3);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (16, 2, 'Avalanche', 376, 1, 4);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (17, 2, 'Blue Eyed Boy', 290, 1, 5);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (18, 2, 'Suzy May', 331, 1, 6);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (19, 2, 'Swamp', 217, 1, 7);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (20, 2, 'Wish', 310, 1, 8);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (21, 2, 'Coming Home', 329, 1, 9);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (22, 2, 'Ages', 348, 1, 10);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (23, 2, 'Recovery', 340, 1, 11);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (24, 2, 'Little Boy', 216, 1, 12);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (25, 3, 'Damage', 390, 1, 1);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (26, 3, 'Overkill', 218, 1, 2);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (27, 3, 'Like A Book', 215, 1, 3);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (28, 3, 'Same Ground Again', 280, 1, 4);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (29, 3, 'Guilty', 210, 1, 5);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (30, 3, 'Chances', 215, 1, 6);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (31, 3, 'Out Of This World', 292, 1, 7);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (32, 3, 'Wish You Were Here', 298, 1, 8);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (33, 3, 'Thief', 276, 1, 9);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (34, 3, 'Under Fire', 238, 1, 10);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (35, 3, 'Not Enough Love', 317, 1, 11);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (36, 3, 'Cruel Heart', 254, 1, 12);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (37, 3, 'Professional Friend', 200, 1, 13);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (38, 3, 'Analogue Street Dub', 342, 1, 14);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (39, 3, 'Marching Orders', 301, 1, 15);
INSERT INTO compositions (comp_id, artf_id, comp_title, comp_duration, comp_disk_num, comp_num) VALUES (40, 3, 'Your Life', 243, 1, 16);
